name: Node.js application CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Build the application
        run: npm install
      - name: Test the application
        run: npm run test:unit
      - name: Display SoftUni username
        run: echo "Martin13s18"
